given_numbers = {'.\\testset\\small\\025.txt', '.\\testset\\small\\065.txt', '.\\testset\\small\\067.txt', '.\\testset\\small\\081.txt', '.\\testset\\small\\083.txt', '.\\testset\\small\\023.txt', '.\\testset\\small\\027.txt', '.\\testset\\small\\070.txt', '.\\testset\\small\\028.txt', '.\\testset\\small\\084.txt', '.\\testset\\small\\041.txt', '.\\testset\\small\\053.txt', '.\\testset\\small\\054.txt', '.\\testset\\small\\031.txt', '.\\testset\\small\\086.txt', '.\\testset\\small\\089.txt', '.\\testset\\small\\073.txt', '.\\testset\\small\\093.txt', '.\\testset\\small\\059.txt', '.\\testset\\small\\092.txt', '.\\testset\\small\\032.txt', '.\\testset\\small\\076.txt', '.\\testset\\small\\048.txt', '.\\testset\\small\\056.txt', '.\\testset\\small\\012.txt', '.\\testset\\small\\036.txt', '.\\testset\\small\\082.txt', '.\\testset\\small\\057.txt', '.\\testset\\small\\035.txt', '.\\testset\\small\\038.txt', '.\\testset\\small\\097.txt', '.\\testset\\small\\030.txt', '.\\testset\\small\\095.txt', '.\\testset\\small\\061.txt', '.\\testset\\small\\055.txt', '.\\testset\\small\\015.txt', '.\\testset\\small\\049.txt', '.\\testset\\small\\011.txt', '.\\testset\\small\\022.txt', '.\\testset\\small\\087.txt', '.\\testset\\small\\100.txt', '.\\testset\\small\\078.txt', '.\\testset\\small\\071.txt', '.\\testset\\small\\064.txt', '.\\testset\\small\\047.txt', '.\\testset\\small\\001.txt', '.\\testset\\small\\016.txt', '.\\testset\\small\\004.txt', '.\\testset\\small\\017.txt', '.\\testset\\small\\044.txt', '.\\testset\\small\\024.txt', '.\\testset\\small\\021.txt', '.\\testset\\small\\085.txt', '.\\testset\\small\\058.txt', '.\\testset\\small\\077.txt', '.\\testset\\small\\009.txt', '.\\testset\\small\\007.txt', '.\\testset\\small\\026.txt', '.\\testset\\small\\050.txt', '.\\testset\\small\\060.txt', '.\\testset\\small\\039.txt', '.\\testset\\small\\090.txt', '.\\testset\\small\\079.txt', '.\\testset\\small\\080.txt', '.\\testset\\small\\008.txt', '.\\testset\\small\\002.txt', '.\\testset\\small\\005.txt', '.\\testset\\small\\046.txt', '.\\testset\\small\\019.txt', '.\\testset\\small\\052.txt', '.\\testset\\small\\006.txt', '.\\testset\\small\\096.txt', '.\\testset\\small\\018.txt', '.\\testset\\small\\088.txt', '.\\testset\\small\\013.txt', '.\\testset\\small\\034.txt', '.\\testset\\small\\040.txt', '.\\testset\\small\\045.txt', '.\\testset\\small\\020.txt', '.\\testset\\small\\098.txt', '.\\testset\\small\\063.txt', '.\\testset\\small\\072.txt', '.\\testset\\small\\099.txt', '.\\testset\\small\\043.txt', '.\\testset\\small\\066.txt', '.\\testset\\small\\042.txt', '.\\testset\\small\\069.txt', '.\\testset\\small\\003.txt', '.\\testset\\small\\062.txt', '.\\testset\\small\\029.txt', '.\\testset\\small\\075.txt', '.\\testset\\small\\010.txt', '.\\testset\\small\\033.txt', '.\\testset\\small\\014.txt', '.\\testset\\small\\091.txt', '.\\testset\\small\\051.txt'}

# Extract the numbers from the file names
given_numbers = {int(name.split('\\')[-1].split('.')[0]) for name in given_numbers}

all_numbers = set(range(1, 101))  # All numbers from 1 to 100

missing_numbers = all_numbers - given_numbers

print(missing_numbers)